//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirBnb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatPhong()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int MaDon { get; set; }
        public System.DateTime NgayDat { get; set; }
        public decimal TongChiPhi { get; set; }
        public int MaPhong { get; set; }
        public int MaKH { get; set; }
        public Nullable<int> SoNgayThue { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual KhachThue KhachThue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
