//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirBnb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHoaDon { get; set; }
        public System.DateTime NgayTao { get; set; }
        public int MaKH { get; set; }
        public int MaDon { get; set; }
    
        public virtual DonDatPhong DonDatPhong { get; set; }
        public virtual KhachThue KhachThue { get; set; }
    }
}
