//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirBnb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.DanhGias = new HashSet<DanhGia>();
            this.DonDatPhongs = new HashSet<DonDatPhong>();
            this.YeuThiches = new HashSet<YeuThich>();
        }
    
        public int MaPhong { get; set; }
        public string TieuDe { get; set; }
        public string DiaChi { get; set; }
        public string MoTa { get; set; }
        public decimal Gia1Ngay { get; set; }
        public string DieuKhoan { get; set; }
        public bool TinhTrang { get; set; }
        public byte SLKhach { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public Nullable<int> SoNgayO { get; set; }
        public string HinhAnh1 { get; set; }
        public string HinhAnh2 { get; set; }
        public string HinhAnh3 { get; set; }
        public string HinhAnh4 { get; set; }
        public string HinhAnh5 { get; set; }
        public int MaDanhMuc { get; set; }
        public int MaChuNha { get; set; }
        public Nullable<int> MaKM { get; set; }
    
        public virtual ChuNha ChuNha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual DanhMucPhong DanhMucPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatPhong> DonDatPhongs { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuThich> YeuThiches { get; set; }
    }
}
